name: Deploy Hugo SSG to GH Pages

# When the action should run. Here we specify it should run on push to main branch.
# We also allow for manually running the action with the empty "workflow_dispatch".
on:
  push:
    branches:
      - master

  workflow_dispatch:

# Set the needed permissions.
permissions:
  contents: read
  pages: write
  id-token: write

# Cancel running deployments if a new one is issued - avoids any conflicts or overwriting content.
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest # Always pulls latest version of Ubuntu runner.
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setting up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest" # Always pulls latest version of Hugo.
          extended: true

      - name: Remove public dir
        run: rm -rf public # delete the public directory (our published output folder) before build so stale content is not kept.

      - name: Setting up Pages
        id: pages
        uses: actions/configure-pages@v2

      - name: Build
        run: hugo --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy build to GH Pages
        id: deployment
        uses: actions/deploy-pages@v1
